// SPDX-FileCopyrightText: 2025 Andrew Whewell
// SPDX-License-Identifier: BSD-3-Clause

namespace WwDevicesDotNet
{
    /// <summary>
    /// An enumeration of all of the keys on the MCDU.
    /// </summary>
    public enum Key
    {
        LineSelectLeft1,
        LineSelectLeft2,
        LineSelectLeft3,
        LineSelectLeft4,
        LineSelectLeft5,
        LineSelectLeft6,
        LineSelectRight1,
        LineSelectRight2,
        LineSelectRight3,
        LineSelectRight4,
        LineSelectRight5,
        LineSelectRight6,

        Airport,
        Altn,
        AtcComm,
        Atc,
        Blank1,
        Blank2,
        Brt,
        Clb,
        Crz,
        Data,
        DepArr,
        Des,
        Dim,
        Dir,
        Exec,
        Fix,
        FmcComm,
        FPln,
        FuelPred,
        Hold,
        Init,
        InitRef,
        Legs,
        McduMenu,
        Menu,
        N1Limit,
        NavRad,
        NextPage,
        Perf,
        PrevPage,
        Prog,
        RadNav,
        Rte,
        SecFPln,
        VNav,

        LeftArrow,
        UpArrow,
        RightArrow,
        DownArrow,

        Digit1,
        Digit2,
        Digit3,
        Digit4,
        Digit5,
        Digit6,
        Digit7,
        Digit8,
        Digit9,
        DecimalPoint,
        Digit0,
        PositiveNegative,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Slash,
        Space,
        Clr,

        Ovfy,
        Del,
    }
}
