// SPDX-FileCopyrightText: 2025 Laurent André
// SPDX-License-Identifier: BSD-3-Clause

namespace WwDevicesDotNet.Winctrl.FcuAndEfis
{
    /// <summary>
    /// An enumeration of all of the buttons and controls on the FCU and EFIS panels.
    /// </summary>
    public enum Control
    {
        // FCU controls
        FcuSpdMach,
        FcuLoc,
        FcuHdgTrkVsFpa,
        FcuAp1,
        FcuAp2,
        FcuAThr,
        FcuExped,
        FcuMetricAlt,
        FcuAppr,
        FcuSpdDec,
        FcuSpdInc,
        FcuSpdPush,
        FcuSpdPull,
        FcuHdgDec,
        FcuHdgInc,
        FcuHdgPush,
        FcuHdgPull,
        FcuAltDec,
        FcuAltInc,
        FcuAltPush,
        FcuAltPull,
        FcuVsDec,
        FcuVsInc,
        FcuVsPush,
        FcuVsPull,
        FcuAlt100,
        FcuAlt1000,

        // Left EFIS controls
        LeftFd,
        LeftLs,
        LeftCstr,
        LeftWpt,
        LeftVorD,
        LeftNdb,
        LeftArpt,
        LeftBaroPush,
        LeftBaroPull,
        LeftBaroDec,
        LeftBaroInc,
        LeftInHg,
        LeftHPa,
        LeftModeLs,
        LeftModeVor,
        LeftModeNav,
        LeftModeArc,
        LeftModePlan,
        LeftRange10,
        LeftRange20,
        LeftRange40,
        LeftRange80,
        LeftRange160,
        LeftRange320,
        LeftNeedle1Adf,
        LeftNeedle1Off,
        LeftNeedle1Vor,
        LeftNeedle2Adf,
        LeftNeedle2Off,
        LeftNeedle2Vor,

        // Right EFIS controls
        RightFd,
        RightLs,
        RightCstr,
        RightWpt,
        RightVorD,
        RightNdb,
        RightArpt,
        RightBaroPush,
        RightBaroPull,
        RightBaroDec,
        RightBaroInc,
        RightInHg,
        RightHPa,
        RightModeLs,
        RightModeVor,
        RightModeNav,
        RightModeArc,
        RightModePlan,
        RightRange10,
        RightRange20,
        RightRange40,
        RightRange80,
        RightRange160,
        RightRange320,
        RightNeedle1Vor,
        RightNeedle1Off,
        RightNeedle1Adf,
        RightNeedle2Vor,
        RightNeedle2Off,
        RightNeedle2Adf,
    }
}
